# Generated by Django 6.0.2 on 2026-09-16 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Property listing title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the property')),
                ('location', models.CharField(help_text='City / Area / Locality', max_length=100)),
                ('address', models.TextField(help_text='Full address of the property')),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent amount in ₹', max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit amount in ₹', max_digits=10)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('ROOM', 'Single Room'), ('SHARED', 'Shared Room')], default='APARTMENT', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('furnished_status', models.CharField(choices=[('FURNISHED', 'Furnished'), ('SEMI', 'Semi-Furnished'), ('UNFURNISHED', 'Unfurnished')], default='UNFURNISHED', max_length=20)),
                ('wifi_available', models.BooleanField(default=False, verbose_name='Wi-Fi Available')),
                ('parking_available', models.BooleanField(default=False, verbose_name='Parking Available')),
                ('other_amenities', models.TextField(blank=True, help_text='Other facilities (e.g. Gym, Power Backup, Elevator, Security)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Rent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Property owner user', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
