# Generated by Django 6.0.2 on 2026-09-16 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_move_in_date', models.DateField(help_text="Tenant's intended move-in date")),
                ('message', models.TextField(blank=True, help_text='Optional message from tenant to property owner')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Property owner receiving the request', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_rental_requests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='Requested rental property', on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='core.property')),
                ('tenant', models.ForeignKey(help_text='Tenant who submitted the rental request', on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Request',
                'verbose_name_plural': 'Rental Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
