# Generated by Django 6.0.2 on 2026-09-16 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rentalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateField(help_text='Lease start date (move-in date)')),
                ('rental_end_date', models.DateField(help_text='Lease agreement end date')),
                ('monthly_rent', models.DecimalField(decimal_places=2, help_text='Monthly rent amount in ₹', max_digits=10)),
                ('rent_due_day', models.PositiveIntegerField(default=5, help_text='Rent due day of the month (1 to 28)')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit amount in ₹', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Property owner', on_delete=django.db.models.deletion.CASCADE, related_name='owner_tenancies', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='Rented property', on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='core.property')),
                ('rental_request', models.OneToOneField(blank=True, help_text='Original rental request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenancy', to='core.rentalrequest')),
                ('tenant', models.ForeignKey(help_text='Tenant renting the property', on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenancy',
                'verbose_name_plural': 'Tenancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
