# Generated by Django 6.0.2 on 2026-09-16 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_month', models.DateField(help_text='Rent month (stored as 1st day of month, e.g., 2026-10-01)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monthly rent amount in ₹', max_digits=10)),
                ('due_date', models.DateField(help_text='Rent payment due date')),
                ('payment_status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE', 'Due'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UPCOMING', max_length=20)),
                ('paid_date', models.DateTimeField(blank=True, help_text='Date and time when payment was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenancy', models.ForeignKey(help_text='Associated tenancy lease', on_delete=django.db.models.deletion.CASCADE, related_name='rent_records', to='core.tenancy')),
            ],
            options={
                'verbose_name': 'Rent Record',
                'verbose_name_plural': 'Rent Records',
                'ordering': ['-rent_month'],
                'constraints': [models.UniqueConstraint(fields=('tenancy', 'rent_month'), name='unique_tenancy_rent_month')],
            },
        ),
    ]
