# Generated by Django 6.0.2 on 2026-09-16 18:57

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rentrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in ₹', max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Debit/Credit Card'), ('NETBANKING', 'Net Banking')], default='UPI', max_length=20)),
                ('transaction_id', models.CharField(default=core.models.generate_transaction_id, help_text='Unique simulated transaction ID', max_length=50, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when payment was processed')),
                ('owner', models.ForeignKey(help_text='Property owner receiving payment', on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='Property for which rent was paid', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.property')),
                ('rent_record', models.OneToOneField(help_text='Associated rent record', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.rentrecord')),
                ('tenant', models.ForeignKey(help_text='Tenant who completed payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-paid_at'],
            },
        ),
    ]
