# Generated by Django 6.0.2 on 2026-09-17 06:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(help_text='Billing month (stored as 1st day of month, e.g., 2026-09-01)')),
                ('electricity_charge', models.DecimalField(decimal_places=2, default=0, help_text='Electricity charge in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('water_charge', models.DecimalField(decimal_places=2, default=0, help_text='Water charge in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_charge', models.DecimalField(decimal_places=2, default=0, help_text='Maintenance charge in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_charge', models.DecimalField(decimal_places=2, default=0, help_text='Other charge in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, help_text='Optional note or breakdown details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when record was created')),
                ('tenancy', models.ForeignKey(help_text='Associated active tenancy lease', on_delete=django.db.models.deletion.CASCADE, related_name='utility_bills', to='core.tenancy')),
            ],
            options={
                'verbose_name': 'Utility Bill',
                'verbose_name_plural': 'Utility Bills',
                'ordering': ['-billing_month', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenancy', 'billing_month'), name='unique_tenancy_utility_billing_month')],
            },
        ),
    ]
