# Generated by Django 6.0.2 on 2026-09-17 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_utilitybill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('WATER', 'Water'), ('FURNITURE', 'Furniture'), ('APPLIANCE', 'Appliance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('title', models.CharField(help_text='Short title describing the problem', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the maintenance issue')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Optional photo of the problem', null=True, upload_to='maintenance_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when request was submitted')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('owner_response', models.TextField(blank=True, help_text='Optional owner response, resolution note, or update')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when work was marked completed', null=True)),
                ('tenancy', models.ForeignKey(help_text='Associated active tenancy', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='core.tenancy')),
                ('tenant', models.ForeignKey(help_text='Tenant submitting the request', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Request',
                'verbose_name_plural': 'Maintenance Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
