# Generated by Django 6.0.2 on 2026-09-17 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenancerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_new_end_date', models.DateField(help_text="Tenant's requested new lease end date")),
                ('message', models.TextField(blank=True, help_text='Optional message from tenant to property owner')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('owner_response', models.TextField(blank=True, help_text='Optional response note from property owner')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when renewal request was submitted')),
                ('tenancy', models.ForeignKey(help_text='Associated active tenancy lease', on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to='core.tenancy')),
                ('tenant', models.ForeignKey(help_text='Tenant requesting lease renewal', on_delete=django.db.models.deletion.CASCADE, related_name='renewal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Renewal Request',
                'verbose_name_plural': 'Renewal Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
